index:
    path: /
    defaults:  { _controller: UserBase\Server\Controller\LoginController::indexAction }

help:
    path: /help
    defaults:  { _controller: UserBase\Server\Controller\SiteController::helpAction }

picture:
    path: /picture/{accountname}
    defaults:  { _controller: UserBase\Server\Controller\SiteController::pictureAction }

js:
    path: /js

bower:
    path: /bower

login:
    path: /login
    defaults:  { _controller: UserBase\Server\Controller\LoginController::loginAction }

login/success:
    path: /login/success
    defaults:  { _controller: UserBase\Server\Controller\LoginController::loginSuccessAction }

logout/success:
    path: /logout/success
    defaults:  { _controller: UserBase\Server\Controller\LoginController::logoutSuccessAction }

signup:
    path: /signup
    defaults:  { _controller: UserBase\Server\Controller\SignupController::signupAction }

signup_submit:
    path: /signup/submit
    defaults:  { _controller: UserBase\Server\Controller\SignupController::signupSubmitAction }

signup_thankyou:
    path: /signup/thankyou/{accountName}
    defaults:  { _controller: UserBase\Server\Controller\SignupController::signupThankYouAction }

# ==== email validation ====
verify_email:
    path: /verify/email/{accountName}
    defaults:  { _controller: UserBase\Server\Controller\VerifyController::verifyEmailAction }

verify_email_link:
    path: /verify/email/{accountName}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\VerifyController::verifyEmailLinkAction }
# ==== mobile validation ====
verify_mobile:
    path: /verify/mobile/{accountName}
    defaults:  { _controller: UserBase\Server\Controller\VerifyController::verifyMobileAction }

password_reset:
    path: /password-reset
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetStartAction }

password_reset_request:
    path: /password-reset/request
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetRequestAction }

password_reset_update:
    path: /password-reset/{username}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetUpdateAction }

password_reset_submit:
    path: /password-reset/submit/{username}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetSubmitAction }

password_reset_mobile_check:
    path: /password-reset/mobile-check/{accountName}
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetMobileCheckAction }

password_reset_sent:
    path: /password-reset/sent
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetSentAction }

password_reset_success:
    path: /password-reset/success
    defaults:  { _controller: UserBase\Server\Controller\PasswordResetController::passwordResetSuccessAction }

# PORTAL
portal_index:
    path: /portal
    defaults:  { _controller: UserBase\Server\Controller\PortalController::indexAction }

portal_add:
    path: /portal/accounts/new
    defaults:  { _controller: UserBase\Server\Controller\PortalController::accountAddAction }

portal_view:
    path: /portal/accounts/{accountname}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::viewAction }

portal_account_picture:
    path: /portal/accounts/{accountname}/picture
    defaults:  { _controller: UserBase\Server\Controller\PortalController::pictureAction }

portal_view:
    path: /portal/accounts/{accountname}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::viewAction }

portal_cropimag:
    path: /portal/accounts/{accountname}/crop
    defaults:  { _controller: UserBase\Server\Controller\PortalController::cropImageAction }

portal_edit:
    path: /portal/accounts/{accountname}/edit
    defaults:  { _controller: UserBase\Server\Controller\PortalController::accountEditAction }

portal_account_members:
    path: /portal/accounts/{accountname}/members
    defaults:  { _controller: UserBase\Server\Controller\PortalController::accountMembersAction }

portal_account_user_add:
    path: /portal/accounts/{accountname}/users/add
    defaults:  { _controller: UserBase\Server\Controller\PortalController::accountUserAddAction }

portal_app_login:
    path: /portal/applogin/{appname}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::appLoginAction }

# SPACE
portal_spaces_add:
    path: /portal/accounts/{accountname}/spaces/add
    defaults:  { _controller: UserBase\Server\Controller\PortalController::addSpaceAction }

portal_spaces_view:
    path: /portal/spaces/{id}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::spaceViewAction }

portal_spaces_edit:
    path: /portal/spaces/edit/{id}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::editSpaceAction }

portal_spaces_delete:
    path: /portal/spaces/delete/{id}
    defaults:  { _controller: UserBase\Server\Controller\PortalController::deleteSpaceAction }

# API
api_v1_root:
    path: /api/v1
    defaults:  { _controller: UserBase\Server\Controller\ApiController::indexAction }

api_v1_user_list:
    path: /api/v1/users
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userIndexAction }

api_v1_user_view:
    path: /api/v1/users/{userName}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userViewAction }

api_v1_account_list:
    path: /api/v1/accounts
    defaults:  { _controller: UserBase\Server\Controller\ApiController::accountIndexAction }

api_v1_account_view:
    path: /api/v1/accounts/{accountName}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::accountViewAction }

api_v1_account_property:
    path: /api/v1/accounts/{accountName}/setProperty/{propertyName}/{propertyValue}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::propertyAction }

api_v1_account_add_user:
    path: /api/v1/accounts/{accountName}/addUser/{userName}/{isAdmin}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userAssignAccountAction }

api_v1_account_delete_user:
    path: /api/v1/accounts/{accountName}/removeUser/{userName}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userRemoveAccountAction }

api_v1_event_add:
    path: /api/v1/accounts/{accountName}/addEvent/{eventName}
    defaults: { _controller: UserBase\Server\Controller\ApiController::addEventAction }

admin_index:
    path: /admin
    defaults:  { _controller: UserBase\Server\Controller\AdminController::indexAction }

admin_log_list:
    path: /admin/logs
    defaults:  { _controller: UserBase\Server\Controller\AdminController::logListAction }

# USER MODULE
admin_user_list:
    path: /admin/users
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userListAction }

admin_user_add:
    path: /admin/users/add
    defaults: { _controller: UserBase\Server\Controller\UserAdminController::userAddAction }

admin_user_check:
    path: /admin/users/check
    defaults: { _controller: UserBase\Server\Controller\UserAdminController::chkUserNameAction }

admin_user_view:
    path: /admin/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userViewAction }

admin_user_tools:
    path: /admin/users/{username}/tools
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userToolsAction }

admin_user_update_password:
    path: /admin/users/{username}/updatepassword
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userUpdatePasswordAction }

admin_user_update_email:
    path: /admin/users/{username}/updateemail
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userUpdateEmailAction }

admin_user_update_displayname:
    path: /admin/users/{username}/updatedisplayname
    defaults:  { _controller: UserBase\Server\Controller\UserAdminController::userUpdateDisplayNameAction }

# ACCOUNT MODULE

admin_account_apikeys:
    path: /admin/apikeys
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::apikeysAction }

admin_account_add:
    path: /admin/accounts/add
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::accountAddAction }

admin_account_list:
    path: /admin/accounts/{accountType}
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::accountListAction, accountType: user }

admin_account_view:
    path: /admin/accounts/{accountname}/view
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::accountViewAction }

admin_account_edit:
    path: /admin/accounts/{accountname}/edit
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::accountEditAction }

admin_account_delete:
    path: /admin/accounts/{accountname}/delete
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::accountDeleteAction }

admin_account_add_apikey:
    path: /admin/accounts/{accountname}/addapikey
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::addApikeyAction }

admin_account_edit_apikey:
    path: /admin/accounts/{accountname}/{id}/editapikey
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::editApikeyAction }

admin_account_add_property:
    path: /admin/accounts/{accountname}/addproperty
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::addPropertyAction }

admin_account_delete_property:
    path: /admin/accounts/{accountname}/deleteproperty/{propertyId}
    defaults:  { _controller: UserBase\Server\Controller\AccountAdminController::deletePropertyAction }

admin_account_users:
    path: /admin/accounts/{accountname}/users
    defaults: {_controller:  UserBase\Server\Controller\AccountAdminController::accountUsersAction }

admin_account_searchuser:
    path: /admin/accounts/{accountname}/searchuser
    defaults: {_controller:  UserBase\Server\Controller\AccountAdminController::accountSearchUserAction }

# APPLICATION MODULE

admin_apps_list:
    path: /admin/apps
    defaults:  { _controller: UserBase\Server\Controller\AppAdminController::appListAction }

admin_app_add:
    path: /admin/apps/add
    defaults: { _controller: UserBase\Server\Controller\AppAdminController::appAddAction }

admin_app_edit:
    path: /admin/apps/{appname}/edit
    defaults: { _controller: UserBase\Server\Controller\AppAdminController::appEditAction }

admin_app_view:
    path: /admin/apps/{appname}
    defaults:  { _controller: UserBase\Server\Controller\AppAdminController::appViewAction }

admin_app_users:
    path: /admin/apps/{appname}/users
    defaults: {_controller:  UserBase\Server\Controller\AppAdminController::appUsersAction }

admin_app_searchuser:
   path: /admin/apps/{appname}/searchuser
   defaults: {_controller:  UserBase\Server\Controller\AppAdminController::appSearchUserAction }

authorize_confirm:
    path: /authorize/confirm/{provider}
    defaults: { _controller: UserBase\Server\Controller\OAuth2Controller::confirmAction }

oauth2_server_authorize:
    path: /oauth2/authorize
    defaults: { _controller: UserBase\Server\Controller\OAuth2ServerController::authorize }

oauth2_server_code:
    path: /oauth2/code
    defaults: { _controller: UserBase\Server\Controller\OAuth2ServerController::code }


oauth2_server_api:
    path: /oauth2/api
    defaults: { _controller: UserBase\Server\Controller\OAuth2ServerController::api }

oauth2:
    path: /authorize/{provider}
    defaults: { _controller: UserBase\Server\Controller\OAuth2Controller::authorizeAction }

admin_app_delete:
    path: /admin/apps/{appname}/delete
    defaults: { _controller: UserBase\Server\Controller\AdminController::appDeleteAction }

# APPLICATION BLACKLIST #

admin_blacklist_index:
    path: /admin/blacklist
    defaults: { _controller: UserBase\Server\Controller\BlacklistController::indexAction }

admin_blacklist_add:
    path: /admin/blacklist/add
    defaults: { _controller: UserBase\Server\Controller\BlacklistController::addAction }

admin_blacklist_edit:
    path: /admin/blacklist/edit/{id}
    defaults: { _controller: UserBase\Server\Controller\BlacklistController::editAction }

admin_blacklist_delete:
    path: /admin/blacklist/delete/{id}
    defaults: { _controller: UserBase\Server\Controller\BlacklistController::deleteAction }

# ACCOUNT TAGS  #
admin_tag_index:
    path: /admin/tags
    defaults: { _controller: UserBase\Server\Controller\TagController::indexAction }

admin_tag_add:
        path: /admin/tags/add
        defaults: { _controller: UserBase\Server\Controller\TagController::addAction }

admin_tag_edit:
    path: /admin/tags/edit/{id}
    defaults: { _controller: UserBase\Server\Controller\TagController::editAction }

admin_account_tags:
    path: /admin/accounts/{accountName}/tags
    defaults: { _controller: UserBase\Server\Controller\AccountTagController::tagAction }

# ACCOUNT CONNECTION #
admin_account_connection_add:
    path: /admin/accounts/{accountName}/connections/add
    defaults: { _controller: UserBase\Server\Controller\AccountConnectionController::addAction }

admin_account_connection_index:
    path: /admin/accounts/{accountName}/connections
    defaults: { _controller: UserBase\Server\Controller\AccountConnectionController::indexAction }

admin_account_connection_delete:
    path: /admin/accounts/{accountName}/connections/{id}/delete
    defaults: { _controller: UserBase\Server\Controller\AccountConnectionController::deleteAction }
